### ISSUE TITLE
idk how to add ur bitonicPixelSorter to unity 20223.3.18f

### ISSUE THREAD

**Issue by youlisse** [ruccho/BitonicPixelSorter#1]
i realy want to play with it so badly
![wut](https://github.com/ruccho/BitonicPixelSorter/assets/46898546/4fd663a9-7a58-4c2e-b0a8-82c5bdf8a71c)

**Comment by ruccho** [comment]
When you are using URP, add **Bitonic Pixel Sorting Feature** to your renderer asset as a renderer feature instead of using Bitonic Pixel Sorter component directly.
![image](https://github.com/ruccho/BitonicPixelSorter/assets/16096562/562d6aac-4087-4161-9ea3-d324e5b55085)
